name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git config user.name github-actions[bot]
      - run: git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup npm auth
        run: |
          echo "registry=https://registry.npmjs.org" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
