name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: git config user.name github-actions[bot]
      - run: git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
          scope: '@felipecesr'
          cache: 'yarn'
        secrets: inherit
      - run: yarn --frozen-lockfile
      - run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
