name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          always-auth: true
          node-version: '20.x'
          registry-url: https://registry.npmjs.org
          scope: '@felipecesr'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
